:concurrency: 5
:queues:
  - default
  - mailers
:redis:
  :url: "redis://localhost:6379/0"

:scheduler:
  :schedule:
    weekly_report:
      cron: "0 14 * * 1" # every monday at 14:00
      class: "WeeklyReportJob"
